baseurl: "/antelope" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://ifwe.github.io" # the base hostname & protocol for your site
githubsrc: "https://www.github.com/ifwe/antelope/tree/master"
googlegroupurl: "https://groups.google.com/forum/#!forum/antelope-rte"
title: "Antelope"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
